http:
  port: 3000
admin:
    host: localhost
    port: 9080    
apiEndpoints:
  plans:
    host: localhost
    paths: "/plan*"
    methods: ["GET", "PUT", "POST", "PATCH", "DELETE"]
serviceEndpoints:
  httpplans:
    url: 'http://localhost:3001'  
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
pipelines:
  default:
    apiEndpoints:
      - plans
    policies:
      - jwt:
        - action:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - proxy:
          - action:
              serviceEndpoint: httpplans      
